---
abstract: 'Define Coercions per attribute!'
author:
  - 'Mike Francis <ungrim97@gmail.com>'
build_requires:
  Data::Dumper: 0
  Test::Most: 0.31
configure_requires:
  Module::Build::Tiny: 0.025
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.3, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-CoercePerAttribute
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Moose: 0
  Moose::Role: 0
  Moose::Util: 0
  Moose::Util::TypeConstraints: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/ungrim97/MooseX-CoercePerAttribute/issues
  homepage: https://github.com/ungrim97/MooseX-CoercePerAttribute
  repository: https://github.com/ungrim97/MooseX-CoercePerAttribute.git
version: 1.000
x_contributors:
  - 'Mike Francis (mrf) <ungrim97@gmail.com>'
