---
abstract: 'Define Coercions per attribute!'
author:
  - 'Mike Francis <ungrim97@gmail.com>'
build_requires:
  Data::Dumper: '0'
  Test::Most: '0.31'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.12.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-CoercePerAttribute
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  MooseX::CoercePerAttribute:
    file: lib/MooseX/CoercePerAttribute.pm
    version: '1.001'
requires:
  Moose: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  Moose::Util::TypeConstraints: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/ungrim97/MooseX-CoercePerAttribute/issues
  homepage: https://github.com/ungrim97/MooseX-CoercePerAttribute
  repository: git://github.com/ungrim97/MooseX-CoercePerAttribute.git
version: '1.001'
x_contributors:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'ungrim97 <ungrim97@hotmail.com>'
