---
abstract: 'Define Coercions per attribute!'
author:
  - 'mrf <mrf@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-CoercePerAttribute
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util: 0
  Moose::Util::TypeConstraints: 0
  Test::More: 0
version: 0.802
